name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  username:  # id of input
    description: 'Who run the repo'
    required: true
    default: 'Github User'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}